# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_fitting = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_fitting.setEnabled(False)
        self.checkBox_fitting.setChecked(False)
        self.checkBox_fitting.setObjectName("checkBox_fitting")
        self.gridLayout.addWidget(self.checkBox_fitting, 14, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 9, 0, 1, 4)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 11, 0, 1, 4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 3, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 2, 2, 3, 1)
        self.lineEdit_channel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_channel.setEnabled(False)
        self.lineEdit_channel.setObjectName("lineEdit_channel")
        self.gridLayout_3.addWidget(self.lineEdit_channel, 4, 1, 1, 1)
        self.checkBox_channel = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_channel.setEnabled(False)
        self.checkBox_channel.setChecked(True)
        self.checkBox_channel.setObjectName("checkBox_channel")
        self.gridLayout_3.addWidget(self.checkBox_channel, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.lineEdit_scale_x_min = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_scale_x_min.setEnabled(False)
        self.lineEdit_scale_x_min.setObjectName("lineEdit_scale_x_min")
        self.gridLayout_3.addWidget(self.lineEdit_scale_x_min, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 6, 1, 1)
        self.comboBox_model = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_model.setEnabled(False)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_model, 3, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 6, 1, 1)
        self.lineEdit_scale_y_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_scale_y_max.setEnabled(False)
        self.lineEdit_scale_y_max.setObjectName("lineEdit_scale_y_max")
        self.gridLayout_3.addWidget(self.lineEdit_scale_y_max, 4, 4, 1, 1)
        self.checkBox_default_scale = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_default_scale.setEnabled(False)
        self.checkBox_default_scale.setChecked(True)
        self.checkBox_default_scale.setObjectName("checkBox_default_scale")
        self.gridLayout_3.addWidget(self.checkBox_default_scale, 0, 4, 1, 1)
        self.lineEdit_scale_x_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_scale_x_max.setEnabled(False)
        self.lineEdit_scale_x_max.setObjectName("lineEdit_scale_x_max")
        self.gridLayout_3.addWidget(self.lineEdit_scale_x_max, 4, 3, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_3.addWidget(self.line_26, 2, 7, 3, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 8)
        self.lineEdit_scale_y_min = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_scale_y_min.setEnabled(False)
        self.lineEdit_scale_y_min.setObjectName("lineEdit_scale_y_min")
        self.gridLayout_3.addWidget(self.lineEdit_scale_y_min, 3, 4, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_3.addWidget(self.line_27, 2, 5, 3, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.gridLayout_3.setColumnStretch(4, 1)
        self.gridLayout_3.setColumnStretch(6, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 8, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.button_data_folder = QtWidgets.QPushButton(self.centralwidget)
        self.button_data_folder.setObjectName("button_data_folder")
        self.gridLayout_7.addWidget(self.button_data_folder, 2, 1, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_7.addWidget(self.line_12, 2, 0, 3, 1)
        self.lineEdit_missing = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_missing.setMouseTracking(False)
        self.lineEdit_missing.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_missing.setObjectName("lineEdit_missing")
        self.gridLayout_7.addWidget(self.lineEdit_missing, 3, 1, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_7.addWidget(self.line_13, 2, 2, 2, 1)
        self.button_guess_model = QtWidgets.QPushButton(self.centralwidget)
        self.button_guess_model.setEnabled(False)
        self.button_guess_model.setObjectName("button_guess_model")
        self.gridLayout_7.addWidget(self.button_guess_model, 3, 3, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_7.addWidget(self.line_16, 1, 0, 1, 5)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 0, 3, 1, 2)
        self.button_x_y = QtWidgets.QPushButton(self.centralwidget)
        self.button_x_y.setEnabled(False)
        self.button_x_y.setObjectName("button_x_y")
        self.gridLayout_7.addWidget(self.button_x_y, 2, 4, 1, 1)
        self.button_area_thickness = QtWidgets.QPushButton(self.centralwidget)
        self.button_area_thickness.setEnabled(False)
        self.button_area_thickness.setObjectName("button_area_thickness")
        self.gridLayout_7.addWidget(self.button_area_thickness, 3, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 1, 1, 1)
        self.button_config = QtWidgets.QPushButton(self.centralwidget)
        self.button_config.setEnabled(False)
        self.button_config.setObjectName("button_config")
        self.gridLayout_7.addWidget(self.button_config, 2, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.gridLayout_7.setColumnStretch(3, 1)
        self.gridLayout_7.setColumnStretch(4, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 1, 0, 2, 4)
        self.button_plot = QtWidgets.QPushButton(self.centralwidget)
        self.button_plot.setEnabled(False)
        self.button_plot.setObjectName("button_plot")
        self.gridLayout.addWidget(self.button_plot, 14, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_6.addWidget(self.checkBox_7, 3, 6, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 3, 5, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_6.addWidget(self.checkBox_6, 2, 6, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 2, 5, 1, 1)
        self.checkBox_freq_range = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_freq_range.setEnabled(False)
        self.checkBox_freq_range.setChecked(True)
        self.checkBox_freq_range.setObjectName("checkBox_freq_range")
        self.gridLayout_6.addWidget(self.checkBox_freq_range, 2, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 2, 0, 2, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 2, 2, 2, 1)
        self.checkBox_freq_point_range = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_freq_point_range.setEnabled(False)
        self.checkBox_freq_point_range.setChecked(True)
        self.checkBox_freq_point_range.setObjectName("checkBox_freq_point_range")
        self.gridLayout_6.addWidget(self.checkBox_freq_point_range, 2, 3, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_freq_min = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_freq_min.setEnabled(False)
        self.lineEdit_freq_min.setObjectName("lineEdit_freq_min")
        self.gridLayout_10.addWidget(self.lineEdit_freq_min, 0, 0, 1, 1)
        self.lineEdit_freq_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_freq_max.setEnabled(False)
        self.lineEdit_freq_max.setObjectName("lineEdit_freq_max")
        self.gridLayout_10.addWidget(self.lineEdit_freq_max, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 3, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_6.addWidget(self.line_11, 1, 0, 1, 10)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 5, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 2, 9, 2, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 8, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 3, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_freq_point_min = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_freq_point_min.setEnabled(False)
        self.lineEdit_freq_point_min.setObjectName("lineEdit_freq_point_min")
        self.gridLayout_11.addWidget(self.lineEdit_freq_point_min, 0, 0, 1, 1)
        self.lineEdit_freq_point_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_freq_point_max.setEnabled(False)
        self.lineEdit_freq_point_max.setObjectName("lineEdit_freq_point_max")
        self.gridLayout_11.addWidget(self.lineEdit_freq_point_max, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_11, 3, 3, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_6.addWidget(self.line_18, 2, 7, 2, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 2, 4, 2, 1)
        self.lineEdit_guess = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_guess.setEnabled(False)
        self.lineEdit_guess.setObjectName("lineEdit_guess")
        self.gridLayout_6.addWidget(self.lineEdit_guess, 3, 8, 1, 1)
        self.checkBox_default_guess = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_default_guess.setEnabled(False)
        self.checkBox_default_guess.setChecked(True)
        self.checkBox_default_guess.setObjectName("checkBox_default_guess")
        self.gridLayout_6.addWidget(self.checkBox_default_guess, 2, 8, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(3, 2)
        self.gridLayout_6.setColumnStretch(5, 1)
        self.gridLayout_6.setColumnStretch(6, 1)
        self.gridLayout_6.setColumnStretch(8, 2)
        self.gridLayout.addLayout(self.gridLayout_6, 10, 0, 1, 4)
        self.button_export = QtWidgets.QPushButton(self.centralwidget)
        self.button_export.setEnabled(False)
        self.button_export.setObjectName("button_export")
        self.gridLayout.addWidget(self.button_export, 14, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 3, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 4)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_config = QtWidgets.QLabel(self.centralwidget)
        self.label_config.setObjectName("label_config")
        self.gridLayout_9.addWidget(self.label_config, 0, 2, 1, 1)
        self.label_data_folder = QtWidgets.QLabel(self.centralwidget)
        self.label_data_folder.setEnabled(True)
        self.label_data_folder.setObjectName("label_data_folder")
        self.gridLayout_9.addWidget(self.label_data_folder, 0, 0, 1, 1)
        self.label_area_thickness = QtWidgets.QLabel(self.centralwidget)
        self.label_area_thickness.setObjectName("label_area_thickness")
        self.gridLayout_9.addWidget(self.label_area_thickness, 1, 2, 1, 1)
        self.label_guess_model = QtWidgets.QLabel(self.centralwidget)
        self.label_guess_model.setObjectName("label_guess_model")
        self.gridLayout_9.addWidget(self.label_guess_model, 2, 0, 1, 1)
        self.label_x_y = QtWidgets.QLabel(self.centralwidget)
        self.label_x_y.setObjectName("label_x_y")
        self.gridLayout_9.addWidget(self.label_x_y, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_9.addWidget(self.line_8, 0, 1, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 5, 0, 1, 4)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timeout.setEnabled(False)
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.gridLayout_4.addWidget(self.lineEdit_timeout, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 14, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Impedance"))
        self.checkBox_fitting.setText(_translate("MainWindow", "Apply Fitting"))
        self.lineEdit_channel.setToolTip(_translate("MainWindow", "Enter a channel"))
        self.lineEdit_channel.setText(_translate("MainWindow", "1"))
        self.lineEdit_channel.setPlaceholderText(_translate("MainWindow", "Enter a Channel"))
        self.checkBox_channel.setText(_translate("MainWindow", "Select all"))
        self.label_4.setText(_translate("MainWindow", "Channels"))
        self.label_3.setText(_translate("MainWindow", "Filter"))
        self.label_5.setText(_translate("MainWindow", "Scale"))
        self.lineEdit_scale_x_min.setPlaceholderText(_translate("MainWindow", "min"))
        self.label_7.setText(_translate("MainWindow", "x-axis"))
        self.label_6.setText(_translate("MainWindow", "y-axis"))
        self.label_15.setText(_translate("MainWindow", "Select: Model"))
        self.comboBox_model.setItemText(0, _translate("MainWindow", "randles"))
        self.label_14.setText(_translate("MainWindow", "Model"))
        self.lineEdit_scale_y_max.setPlaceholderText(_translate("MainWindow", "max"))
        self.checkBox_default_scale.setText(_translate("MainWindow", "Use default Scale"))
        self.lineEdit_scale_x_max.setPlaceholderText(_translate("MainWindow", "max"))
        self.lineEdit_scale_y_min.setPlaceholderText(_translate("MainWindow", "min"))
        self.label.setText(_translate("MainWindow", "Load Folder/Files"))
        self.button_data_folder.setText(_translate("MainWindow", "Data Folder"))
        self.lineEdit_missing.setPlaceholderText(_translate("MainWindow", "Missing Channels: 1, 2, 4-6"))
        self.button_guess_model.setText(_translate("MainWindow", "Guess-Model File"))
        self.label_24.setText(_translate("MainWindow", "Parameter and Other files"))
        self.button_x_y.setText(_translate("MainWindow", "x y File"))
        self.button_area_thickness.setText(_translate("MainWindow", "Area-Thickness File"))
        self.label_23.setText(_translate("MainWindow", "Data Folder with missing Channels"))
        self.button_config.setText(_translate("MainWindow", "Config File"))
        self.button_plot.setText(_translate("MainWindow", "Plot"))
        self.checkBox_7.setText(_translate("MainWindow", "Con"))
        self.checkBox_4.setText(_translate("MainWindow", "x y"))
        self.checkBox_6.setText(_translate("MainWindow", "R"))
        self.checkBox_3.setText(_translate("MainWindow", "Title"))
        self.checkBox_freq_range.setText(_translate("MainWindow", "Use Default Range"))
        self.checkBox_freq_point_range.setText(_translate("MainWindow", "Use Default Range"))
        self.lineEdit_freq_min.setText(_translate("MainWindow", "min"))
        self.lineEdit_freq_min.setPlaceholderText(_translate("MainWindow", "min"))
        self.lineEdit_freq_max.setPlaceholderText(_translate("MainWindow", "max"))
        self.label_10.setText(_translate("MainWindow", "Titles"))
        self.label_13.setText(_translate("MainWindow", "Initial Guess"))
        self.label_9.setText(_translate("MainWindow", "Frequency Range"))
        self.label_11.setText(_translate("MainWindow", "Frequency Points Range"))
        self.lineEdit_freq_point_min.setText(_translate("MainWindow", "min"))
        self.lineEdit_freq_point_min.setPlaceholderText(_translate("MainWindow", "min"))
        self.lineEdit_freq_point_max.setPlaceholderText(_translate("MainWindow", "max"))
        self.lineEdit_guess.setText(_translate("MainWindow", "0.01,0.005,0.1,0.001,200"))
        self.checkBox_default_guess.setText(_translate("MainWindow", "Use Default guess"))
        self.button_export.setText(_translate("MainWindow", "Export"))
        self.label_2.setText(_translate("MainWindow", "Settings & Options"))
        self.label_config.setText(_translate("MainWindow", "Config File:"))
        self.label_data_folder.setText(_translate("MainWindow", "Data Folder:"))
        self.label_area_thickness.setText(_translate("MainWindow", "Area-Thickness File:"))
        self.label_guess_model.setText(_translate("MainWindow", "Guess-Modal File:"))
        self.label_x_y.setText(_translate("MainWindow", "x y File:"))
        self.label_22.setText(_translate("MainWindow", "Selected Folder/Files"))
        self.label_12.setText(_translate("MainWindow", "Plot"))
        self.label_8.setText(_translate("MainWindow", "Fitting Timeout (s): "))
        self.lineEdit_timeout.setText(_translate("MainWindow", "5"))


