# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/app.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_master_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_master_file.setObjectName("button_master_file")
        self.gridLayout.addWidget(self.button_master_file, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_outlier = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outlier.setText("")
        self.lineEdit_outlier.setObjectName("lineEdit_outlier")
        self.gridLayout_3.addWidget(self.lineEdit_outlier, 2, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_3.addWidget(self.line_18, 0, 1, 1, 1)
        self.button_ternary_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_ternary_file.setObjectName("button_ternary_file")
        self.gridLayout_3.addWidget(self.button_ternary_file, 1, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_3.addWidget(self.line_16, 0, 0, 4, 1)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_3.addWidget(self.line_17, 0, 2, 4, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 3)
        self.button_plot = QtWidgets.QPushButton(self.centralwidget)
        self.button_plot.setEnabled(False)
        self.button_plot.setObjectName("button_plot")
        self.gridLayout.addWidget(self.button_plot, 10, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_6.addWidget(self.line_8, 0, 1, 1, 2)
        self.checkbox_default_color = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_default_color.setEnabled(False)
        self.checkbox_default_color.setChecked(True)
        self.checkbox_default_color.setObjectName("checkbox_default_color")
        self.gridLayout_6.addWidget(self.checkbox_default_color, 1, 1, 1, 2)
        self.lineEdit_max_color = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_max_color.setEnabled(False)
        self.lineEdit_max_color.setObjectName("lineEdit_max_color")
        self.gridLayout_6.addWidget(self.lineEdit_max_color, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 3, 1, 1, 1)
        self.lineEdit_min_color = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_min_color.setEnabled(False)
        self.lineEdit_min_color.setObjectName("lineEdit_min_color")
        self.gridLayout_6.addWidget(self.lineEdit_min_color, 2, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_6.addWidget(self.line_10, 0, 0, 4, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 0, 3, 4, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        self.checkbox_compare = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_compare.setEnabled(False)
        self.checkbox_compare.setChecked(False)
        self.checkbox_compare.setObjectName("checkbox_compare")
        self.gridLayout.addWidget(self.checkbox_compare, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_type_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type_2.setEnabled(False)
        self.comboBox_type_2.setObjectName("comboBox_type_2")
        self.comboBox_type_2.addItem("")
        self.comboBox_type_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_type_2, 1, 7, 1, 1)
        self.comboBox_operation = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_operation.setEnabled(False)
        self.comboBox_operation.setObjectName("comboBox_operation")
        self.comboBox_operation.addItem("")
        self.comboBox_operation.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_operation, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.comboBox_type_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type_1.setEnabled(False)
        self.comboBox_type_1.setObjectName("comboBox_type_1")
        self.comboBox_type_1.addItem("")
        self.comboBox_type_1.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_type_1, 1, 2, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 0, 6, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 0, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setEnabled(True)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 4, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 3, 4, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 0, 5, 4, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 0, 8, 4, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 3, 1)
        self.comboBox_cycle_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_cycle_1.setEnabled(False)
        self.comboBox_cycle_1.setCurrentText("")
        self.comboBox_cycle_1.setObjectName("comboBox_cycle_1")
        self.gridLayout_2.addWidget(self.comboBox_cycle_1, 2, 2, 1, 1)
        self.comboBox_cycle_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_cycle_2.setEnabled(False)
        self.comboBox_cycle_2.setObjectName("comboBox_cycle_2")
        self.gridLayout_2.addWidget(self.comboBox_cycle_2, 2, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 8, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.button_config_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_config_file.setObjectName("button_config_file")
        self.gridLayout.addWidget(self.button_config_file, 1, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_4.addWidget(self.line_11, 0, 1, 1, 1)
        self.button_reset_config = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset_config.setEnabled(False)
        self.button_reset_config.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_reset_config.setObjectName("button_reset_config")
        self.gridLayout_4.addWidget(self.button_reset_config, 1, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_4.addWidget(self.line_14, 0, 0, 4, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_4.addWidget(self.line_15, 0, 2, 4, 1)
        self.button_reset_ternary = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset_ternary.setEnabled(False)
        self.button_reset_ternary.setObjectName("button_reset_ternary")
        self.gridLayout_4.addWidget(self.button_reset_ternary, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 5, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 20))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGitHub = QtWidgets.QAction(MainWindow)
        self.actionGitHub.setObjectName("actionGitHub")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionGitHub)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_master_file.setText(_translate("MainWindow", "Open Master File"))
        self.label_2.setText(_translate("MainWindow", "Plots"))
        self.lineEdit_outlier.setPlaceholderText(_translate("MainWindow", "Enter Outlier"))
        self.button_ternary_file.setText(_translate("MainWindow", "Open Ternary File"))
        self.button_plot.setText(_translate("MainWindow", "Plot Ternay Diagram"))
        self.label_9.setText(_translate("MainWindow", "Min:"))
        self.checkbox_default_color.setText(_translate("MainWindow", "Use default color scaling"))
        self.label_10.setText(_translate("MainWindow", "Max:"))
        self.checkbox_compare.setText(_translate("MainWindow", "Compare"))
        self.label_11.setText(_translate("MainWindow", "Reset"))
        self.comboBox_type_2.setItemText(0, _translate("MainWindow", "Average Voltage"))
        self.comboBox_type_2.setItemText(1, _translate("MainWindow", "Charge"))
        self.comboBox_operation.setItemText(0, _translate("MainWindow", "Subtract (-)"))
        self.comboBox_operation.setItemText(1, _translate("MainWindow", "Multiple (*)"))
        self.label_5.setText(_translate("MainWindow", "Select Cycle:"))
        self.label_4.setText(_translate("MainWindow", "Select Type:"))
        self.comboBox_type_1.setItemText(0, _translate("MainWindow", "Average Voltage"))
        self.comboBox_type_1.setItemText(1, _translate("MainWindow", "Charge"))
        self.label_6.setText(_translate("MainWindow", "Select Type:"))
        self.label_7.setText(_translate("MainWindow", "Select Cycle:"))
        self.label_8.setText(_translate("MainWindow", "Operation"))
        self.label_3.setText(_translate("MainWindow", "Plot Control"))
        self.label.setText(_translate("MainWindow", "Load Files"))
        self.button_config_file.setText(_translate("MainWindow", "Open Config File"))
        self.button_reset_config.setText(_translate("MainWindow", "Reset Config"))
        self.button_reset_ternary.setText(_translate("MainWindow", "Reset Input"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))


